apiDeclarations:
  -
    apiVersion: 1
    swaggerVersion: 1.2
    basePath: "http://localhost:8002/api"
    description: "Operations for Albums"
    resourcePath: "/albums"
    produces:
      - "application/json"
      - "application/xml"
    consumes:
      - "application/json"
      - "application/xml"
    apis:
      -
        path: "/albums"
        operations:
          -
            method: "GET"
            summary: "Retrieve albums of the user."
            notes: "Returns a list of all albums for the user."
            type: "array"
            items:
              $ref: "Album"
            nickname: "getAlbums"
            parameters:
              -
                name: "quality"
                paramType: "query"
                description: "The quality of the album"
                type: "string"
                enum:
                  - "good"
                  - "bad"
                  - "terrible"
                required: true
              -
                name: "limit"
                description: "The maximum number of records to return.  Depending on the data, less values may be returned"
                required: false
                type: "integer"
                format: "int64"
                paramType: "query"
                minimum: 1
                maximum: 20
                defaultValue: 10
              -
                name: "skip"
                description: "An offset for the first record to retrieve.  If there are less records than the skip, an empty result will be returned"
                required: false
                type: "integer"
                format: "int64"
                paramType: "query"
                minimum: 0
                defaultValue: 0
          -
            method: "POST"
            summary: "Create a new album."
            notes: "Create a new album for the logged in user and returns its ID."
            type: "ID"
            nickname: "createAlbum"
            parameters:
              -
                name: "body"
                description: "The new album to be created."
                required: true
                type: "InputAlbum"
                paramType: "body"
            responseMessages:
              -
                code: 400
                message: "Invalid input."
      -
        path: "/albums/{albumId}"
        operations:
          -
            method: "GET"
            summary: "Retrieve a specific album."
            notes: "Returns a specific album of the logged-in user."
            type: "Album"
            nickname: "getAlbum"
            parameters:
              -
                name: "albumId"
                description: "The ID of the album to retrieve."
                required: true
                type: "integer"
                format: "int64"
                paramType: "path"
            responseMessages:
              -
                code: 404
                message: "Album not found."
          -
            method: "DELETE"
            summary: "Deletes an album."
            notes: "Deletes an album for the logged-in user."
            type: "void"
            nickname: "deleteAlbum"
            parameters:
              -
                name: "albumId"
                description: "The ID of the album to retrieve."
                required: true
                type: "integer"
                format: "int64"
                paramType: "path"
            responseMessages:
              -
                code: 404
                message: "Album not found."
          -
            method: "PATCH"
            summary: "Updates an album."
            notes: "Updates an album for the logged-in user."
            type: "void"
            nickname: "updateAlbum"
            parameters:
              -
                name: "albumId"
                description: "The ID of the album to retrieve."
                required: true
                type: "integer"
                format: "int64"
                paramType: "path"
              -
                name: "body"
                description: "The updated album."
                required: true
                type: "InputAlbum"
                paramType: "body"
            responseMessages:
              -
                code: 404
                message: "Album not found."
