swagger: 2.0
info:
  version: 1.0.0
  title: petstore
host: example.com
basePath: /api
schemes:
  - http
paths:
  /users:
    get:
      responses:
        200:
          description:  this is a test
