language: node_js
node_js:
  - '0.10'
  # - 'iojs' # iojs is not supported in nvm used in TravisCI. Commented out for now
install:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - npm install -g npm@2
  - npm cache clean
  - npm install
  - ./node_modules/bower/bin/bower install
