language: node_js
node_js:
  - '0.8'
  - '0.10'
install: gem install compass
before_script:
  - 'gem install compass'
  - 'npm install -g bower grunt-cli'
  - 'bower install'
  - 'grunt build'
rvm:
  - 2.0.0
